author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2021-01-02
description = Analyze a package and search for 'dead' code
tags = C81
min-version = 2020a
public = get_pkgdata function_statistics print_pkgsummary
help = pkgchecker_help.txt
sample-script = pkgchecker_sample.inp
data-requirement = no-data-ok
